package TicTacToe;

import java.awt.AWTException;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;

import javax.swing.JOptionPane;

/**
 *
 * @author Hieu
 */
public class End extends javax.swing.JFrame {

    private final String u1, u2;
    Random rand = new Random();
    private int r = rand.nextInt(255);
    private int g = rand.nextInt(255);
    private int b = rand.nextInt(255);
    private Color c1 = new Color(r, g, b);
    private Color c2 = new Color(r / 2, g / 2, b / 2);

    /**
     * Creates new form End
     * @throws AWTException 
     * @throws IOException 
     * @throws HeadlessException 
     */
    public End(String s, String u1, String u2, Color c1, Color c2)  {
        initComponents();
        setLocationRelativeTo(null);
        this.u1 = u1;
        this.u2 = u2;
        this.c1 = c1;
        this.c2 = c2;
        result.setText(s + " wins");
        jPanel1.setBackground(c1);
        newGameBtn.setBackground(c2);
        replayBtn.setBackground(c2);
        printBtn.setBackground(c2);
        exitBtn.setBackground(c2);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        result = new javax.swing.JTextField();
        newGameBtn = new javax.swing.JButton();
        replayBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        setTitle("Result");
        setResizable(false);


        result.setEditable(false);
        result.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        result.setForeground(new java.awt.Color(0, 0, 204));
        result.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        
        newGameBtn.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        newGameBtn.setForeground(new java.awt.Color(255, 255, 255));
        newGameBtn.setText("New Game");
        newGameBtn.setToolTipText("New game with the new players");
        newGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameBtnActionPerformed(evt);
            }
        });

       
        replayBtn.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        replayBtn.setForeground(new java.awt.Color(255, 255, 255));
        replayBtn.setText("Replay");
        replayBtn.setToolTipText("Replay the game with the same players");
        replayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replayBtnActionPerformed(evt);
            }
        });

        
        printBtn.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        printBtn.setForeground(new java.awt.Color(255, 255, 255));
        printBtn.setText("Print");
        printBtn.setToolTipText("Print the result to winners.txt file");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					printBtnActionPerformed(evt);
				} catch (HeadlessException | IOException | AWTException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        
        exitBtn.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Exit");
        exitBtn.setToolTipText("Exit the game");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Tic Tac Toe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newGameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(result, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(replayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(printBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(newGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(replayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        int yesno = JOptionPane.YES_NO_OPTION;
        int yesno_result = JOptionPane.showConfirmDialog(this, "Would you like to exit the game?", "Exit", yesno);
        if(yesno_result == 0) {
           System.exit(0);
        }
        
    }//GEN-LAST:event_exitBtnActionPerformed

    private void replayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replayBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Play(u1, u2, c1, c2).setVisible(true);
    }//GEN-LAST:event_replayBtnActionPerformed

    private void newGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Start().setVisible(true);
    }//GEN-LAST:event_newGameBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) throws HeadlessException, IOException, AWTException {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
        try {
            File file = new File("winners.txt");
            FileWriter fw;

            fw = new FileWriter(file, true);

            BufferedWriter w = new BufferedWriter(fw);

            w.write(result.getText());
            w.newLine();
            w.close();
        } catch (IOException e) {
            System.out.println("Write to files error");
        }
        System.out.println(result.getText());
        JOptionPane.showMessageDialog(rootPane, "Print Successfully");
        
        
    }//GEN-LAST:event_printBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private int x, y, width, height;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newGameBtn;
    private javax.swing.JButton printBtn;
    private javax.swing.JButton replayBtn;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}
