package TicTacToe;

import java.awt.Color;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hieu
 */
public class Start extends javax.swing.JFrame {
	 Random rand = new Random();
     private int r = rand.nextInt(255);
     private int g = rand.nextInt(255);
     private int b = rand.nextInt(255);
     private Color c1 = new Color(r, g, b);
     private Color c2 = new Color(r / 2, g / 2, b / 2);

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        jPanel1.setBackground(c1);
        startBtn.setBackground(c2);
        colorBtn.setBackground(c2);
        aboutBtn.setBackground(c2);
        exitBtn.setBackground(c2);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        player1 = new javax.swing.JTextField();
        player2 = new javax.swing.JTextField();
        startBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        colorBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        setTitle("Tic Tac Toe");
        setBackground(new java.awt.Color(153, 255, 153));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 480));

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Player 1:");

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Player 2:");

        player1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        player1.setToolTipText("Enter the Player 1's Name");
        player1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                player1KeyReleased(evt);
            }
        });

        player2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        player2.setToolTipText("Enter the Player 2's name");
        player2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                player2KeyReleased(evt);
            }
        });

        startBtn.setBackground(new java.awt.Color(47, 238, 172));
        startBtn.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        startBtn.setForeground(new java.awt.Color(255, 255, 255));
        startBtn.setText("Start");
        startBtn.setToolTipText("Start button will be enabled once two players enter their names");
        startBtn.setEnabled(false);
        startBtn.setName(""); // NOI18N
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(47, 238, 172));
        exitBtn.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Exit");
        exitBtn.setToolTipText("Exit the game");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        aboutBtn.setBackground(new java.awt.Color(47, 238, 172));
        aboutBtn.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtn.setText("About");
        aboutBtn.setToolTipText("Information about this game");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });

        colorBtn.setBackground(new java.awt.Color(47, 238, 172));
        colorBtn.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        colorBtn.setForeground(new java.awt.Color(255, 255, 255));
        colorBtn.setText("Change Color");
        colorBtn.setToolTipText("Change the background and button colors");
        colorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorBtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tictactoe.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(player1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(colorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        int yesno = JOptionPane.YES_NO_OPTION;
        int yesno_result = JOptionPane.showConfirmDialog(this, "Would you like to exit the game?", "Exit", yesno);
        if (yesno_result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void player1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_player1KeyReleased
        // TODO add your handling code here:
        if (player1.getText().equals("") || player2.getText().equals("")) {
            startBtn.setEnabled(false);
        } else {
            startBtn.setEnabled(true);
        }
    }//GEN-LAST:event_player1KeyReleased

    private void player2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_player2KeyReleased
        // TODO add your handling code here:
        if (player1.getText().equals("") || player2.getText().equals("")) {
            startBtn.setEnabled(false);
        } else {
            startBtn.setEnabled(true);
        }
    }//GEN-LAST:event_player2KeyReleased

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            if (player1.getText().length() >= 10 || player2.getText().length() >= 10) {
                throw new Exception();
            }
            new Play(player1.getText(), player2.getText(), c1, c2).setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Name is long. Please enter the name between 1 - 10 characters");
            this.setVisible(true);
        }


    }//GEN-LAST:event_startBtnActionPerformed

    private void colorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorBtnActionPerformed
        // TODO add your handling code here:
    	Random rand = new Random();
        int r = rand.nextInt(255);
        int g = rand.nextInt(255);
        int b = rand.nextInt(255);
    	Color c1 = new Color(r, g, b);
        Color c2 = new Color(r / 2, g / 2, b / 2);
        this.c1 = c1;
        this.c2 = c2;
        jPanel1.setBackground(c1);
        startBtn.setBackground(c2);
        colorBtn.setBackground(c2);
        aboutBtn.setBackground(c2);
        exitBtn.setBackground(c2);

    }//GEN-LAST:event_colorBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new About(r, g, b).setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton colorBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField player1;
    private javax.swing.JTextField player2;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
